#!/bin/bash
echo -e
echo -e
echo -e
echo "'##::::'##:'####:'########::'########:::'#######::'########::'##::::'##::'######:::'######::";
echo " ###::'###:. ##:: ##.... ##: ##.... ##:'##.... ##: ##.... ##:. ##::'##::'##... ##:'##... ##:";
echo " ####'####:: ##:: ##:::: ##: ##:::: ##: ##:::: ##: ##:::: ##::. ##'##::: ##:::..:: ##:::..::";
echo " ## ### ##:: ##:: ########:: ########:: ##:::: ##: ########::::. ###::::. ######::. ######::";
echo " ##. #: ##:: ##:: ##.. ##::: ##.. ##::: ##:::: ##: ##.. ##::::: ## ##::::..... ##::..... ##:";
echo " ##:.:: ##:: ##:: ##::. ##:: ##::. ##:: ##:::: ##: ##::. ##::: ##:. ##::'##::: ##:'##::: ##:";
echo " ##:::: ##:'####: ##:::. ##: ##:::. ##:. #######:: ##:::. ##: ##:::. ##:. ######::. ######::";
echo "..:::::..::....::..:::::..::..:::::..:::.......:::..:::::..::..:::::..:::......::::......:::";
echo -e
echo -e
printf "Author: Kaue Navarro\n"
echo -e
printf  "Apimapssearch 1.0 https://github.com/kauenavarroBR\n"
echo -e
echo -e "####### Exemplo de Uso ######"
echo -e
echo -e "     ./Apimapssearch dominio     "
echo -e
echo -e

domain="$1"


subfinder -d $domain -silent | httpx -silent -threads 1000 | xargs -I@ sh -c 'findomain-linux -t @ -q | httpx -mc 200 -silent | anew | waybackurls | anew subdominiosapi.txt'

for payload in $(cat subdominiosapi.txt) ;do HTTP_CODE=$(curl -s $payload  | grep -Eoi  "AIzaSy[0-9A-Za-z_-]{33}" )

var="$payload.$HTTP_CODE"

echo "$var"
if ["$HTTP_CODE"];then
    
   var=$(./gmapsapiscanner/python3 maps_api_scanner_python3.py --api-key $HTTP_CODE)
   else
if
done



