#!/bin/bash
echo -e
echo -e
echo -e
echo "'##::::'##:'####:'########::'########:::'#######::'########::'##::::'##::'######:::'######::";
echo " ###::'###:. ##:: ##.... ##: ##.... ##:'##.... ##: ##.... ##:. ##::'##::'##... ##:'##... ##:";
echo " ####'####:: ##:: ##:::: ##: ##:::: ##: ##:::: ##: ##:::: ##::. ##'##::: ##:::..:: ##:::..::";
echo " ## ### ##:: ##:: ########:: ########:: ##:::: ##: ########::::. ###::::. ######::. ######::";
echo " ##. #: ##:: ##:: ##.. ##::: ##.. ##::: ##:::: ##: ##.. ##::::: ## ##::::..... ##::..... ##:";
echo " ##:.:: ##:: ##:: ##::. ##:: ##::. ##:: ##:::: ##: ##::. ##::: ##:. ##::'##::: ##:'##::: ##:";
echo " ##:::: ##:'####: ##:::. ##: ##:::. ##:. #######:: ##:::. ##: ##:::. ##:. ######::. ######::";
echo "..:::::..::....::..:::::..::..:::::..:::.......:::..:::::..::..:::::..:::......::::......:::";
echo -e
echo -e
printf "Author: Kaue Navarro\n"
echo -e
printf  "Apimapssearch 1.0 https://github.com/kauenavarroBR\n"
echo -e
echo -e "####### Exemplo de Uso ######"
echo -e
echo -e "     ./Apimapssearch dominio     "
echo -e
echo -e

#oldIFS=$IFS 
#IFS=$'\n'
#domain="$1"
#wordlist=$2"
#Renewlist=$(rm xssvalid.txt xssinvalid.txt)
#xssvalid=$(touch xssvalid.txt)
#xssinvalid=$(touch xssinvalid.txt)


#subfinder -d $domain -silent | httpx -silent -threads 1000 | xargs -I@ sh -c 'findomain-linux -t @ -q | httpx -mc 200 -silent | anew | waybackurls | anew subdominiosapi.txt'

for payload in $(cat subdominiosapi.txt) ;do HTTP_CODE=$(curl -s $payload  | grep -Eoi  "AIzaSy[0-9A-Za-z_-]{33}" )

var="$payload.$HTTP_CODE"

echo "$var"
if ["$HTTP_CODE"];then
    
   var=$(./gmapsapiscanner/python3 maps_api_scanner_python3.py --api-key $HTTP_CODE)
   else
if
done
#var6=$(cat xssvalid.txt | aquatone)
#var3=$(wc -l xssvalid.txt)
#var4=$(wc -l xssinvalid.txt)
#echo -e
#echo -e Were found XSS VALID \e[36m${var3}\e[0m  XSS INVALID \e[36m${var4}\e[0m"


#IFS=$old_IFS 
