#!/bin/bash
echo -e
echo -e
echo -e
echo ":::'###::::'########::'####:'##::::'##::::'###::::'########:::'######:::'######::'########::::'###::::'########:::'######::'##::::'##:";
echo "::'## ##::: ##.... ##:. ##:: ###::'###:::'## ##::: ##.... ##:'##... ##:'##... ##: ##.....::::'## ##::: ##.... ##:'##... ##: ##:::: ##:";
echo ":'##:. ##:: ##:::: ##:: ##:: ####'####::'##:. ##:: ##:::: ##: ##:::..:: ##:::..:: ##::::::::'##:. ##:: ##:::: ##: ##:::..:: ##:::: ##:";
echo "'##:::. ##: ########::: ##:: ## ### ##:'##:::. ##: ########::. ######::. ######:: ######:::'##:::. ##: ########:: ##::::::: #########:";
echo " #########: ##.....:::: ##:: ##. #: ##: #########: ##.....::::..... ##::..... ##: ##...:::: #########: ##.. ##::: ##::::::: ##.... ##:";
echo " ##.... ##: ##::::::::: ##:: ##:.:: ##: ##.... ##: ##::::::::'##::: ##:'##::: ##: ##::::::: ##.... ##: ##::. ##:: ##::: ##: ##:::: ##:";
echo " ##:::: ##: ##::::::::'####: ##:::: ##: ##:::: ##: ##::::::::. ######::. ######:: ########: ##:::: ##: ##:::. ##:. ######:: ##:::: ##:";
echo "..:::::..::..:::::::::....::..:::::..::..:::::..::..::::::::::......::::......:::........::..:::::..::..:::::..:::......:::..:::::..::";
echo -e
echo -e
printf "Author: Kaue Navarro\n"
echo -e
printf  "Apimapssearch 1.0 https://github.com/kauenavarroBR\n"
echo -e
echo -e "####### Exemplo de Uso ######"
echo -e
echo -e "     ./Apimapssearch dominio     "
echo -e
echo -e

domain="$1"


subfinder -d $domain -silent | httpx -silent -threads 1000 | xargs -I@ sh -c 'findomain-linux -t @ -q | httpx -mc 200 -silent | anew | waybackurls | anew subdominiosapi.txt'

sleep 5
for payload in $(cat subdominiosapi.txt) ;do api=$(curl -s $payload  | grep -Eoi  "AIzaSy[0-9A-Za-z_-]{33}" )

if [ "$api" == "" ];
 then
echo -e "Api null $payload"
else
varapi=$("$payload-$api")

python3 maps_api_scanner_python3.py --api-key $api

read -p "Continue (y/n)?" CONT
if [ "$CONT" = "y" ]; then
echo""
else
exit
fi
fi
done
