#!/bin/bash
echo -e
echo -e
echo -e
echo ":'######::'##::::'##:'########::'########::'#######::'##::::'##:'####::'######::";
echo "'##... ##: ##:::: ##: ##.... ##:... ##..::'##.... ##: ###::'###:. ##::'##... ##:";
echo " ##:::..:: ##:::: ##: ##:::: ##:::: ##:::: ##:::: ##: ####'####:: ##:: ##:::..::";
echo ". ######:: ##:::: ##: ########::::: ##:::: ##:::: ##: ## ### ##:: ##:: ##:::::::";
echo ":..... ##: ##:::: ##: ##.... ##:::: ##:::: ##:::: ##: ##. #: ##:: ##:: ##:::::::";
echo "'##::: ##: ##:::: ##: ##:::: ##:::: ##:::: ##:::: ##: ##:.:: ##:: ##:: ##::: ##:";
echo ". ######::. #######:: ########::::: ##::::. #######:: ##:::: ##:'####:. ######::";
echo ":......::::.......:::........::::::..::::::.......:::..:::::..::....:::......:::";
sleep 2;
echo "Loading..."
sleep 1;

printf "Author: Kaue Navarro\n"
echo -e
printf  "Subtomic https://github.com/kauenavarroBR\n"
echo -e
echo -e "####### Exemplo de Uso ######"
echo -e
echo -e "     Subtomic dominio     "
echo -e
echo -e

alvo="$1"
mkdir $1
sleep 2;
cd $1
sleep 3;
#Amass + crt
amass enum -src -ip -active -brute -d "$alvo"  -o amass1 ; cat  amass1 | cut -d']' -f 2 | awk '{print $1}' | sort -u >> hosts-amass.txt ; cat  amass1 | cut -d']' -f2 | awk '{print $2}' | tr ',' '\n' | sort -u >> ips-amass.txt ; curl -s "https://crt.sh/?q=%.$alvo&output=json" | jq '.[].name_value' | sed "s/\"//g" | sed "s/\*\.//g" | sort -u >> hosts-crtsh.txt ; sed "s/$/.$alvo/" /home/ferramentas/WORDLISTS/SecLists/Discovery/DNS/dns-Jhaddix.txt >> hosts-wordlist.txt ; cat hosts-amass.txt hosts-crtsh.txt hosts-wordlist.txt | sort -u >> hosts-all.txt 
var1=$(wc -l hosts-amass.txt)
echo "Stage 1 - Complete - Were found $var1"
sleep 2;
echo -e
echo -e
#SubDomainizer
python3 /home/ferramentas/SubDomainizer/SubDomainizer.py -u "https://$alvo" -o stage2

var2=$(wc -l stage2)

echo "Stage 2 - Complete - Were found $var2"
sleep 2;
echo -e
echo -e
#Subginder + Findomain
python3 /home/ferramentas/github-search/github-subdomains.py -t 2cd6526f814274d5dde880703759c61dcd37f846  -d  "$alvo"  | grep -v '[>]' | anew stage3


var3=$(wc -l stage3)

echo "Stage 3 - Complete - Were found $var3"
sleep 2;
echo -e
echo -e

#Virustotal+certspotter+rapiddns+riddler+jldc+crt+dns.bufferover
curl -s "https://www.virustotal.com/ui/domains/$alvo/subdomains?limit=40" | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+" | sort -u >> TARGET-virustotal.txt;curl -s "https://certspotter.com/api/v0/certs?domain=$alvo" | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+" | sort -u >> TARGET-certspotter.txt;
curl -s "https://rapiddns.io/subdomain/$alvo?full=1#result" | awk -v RS='<[^>]+>' '/$1/' | sort -u >>TARGET-rapiddns.txt;curl -s "https://rapiddns.io/subdomain/$alvo?full=1#result" | awk -v RS='<[^>]+>' '/$1/' | sort -u >>TARGET-rapiddns.txt;curl -s "https://riddler.io/search/exportcsv?q=pld:$alvo" | grep -Po "(([\w.-]*)\.([\w]*)\.([A-z]))\w+" | sort -u >>TARGET-riddler.txt;curl -s "https://jldc.me/anubis/subdomains/$alvo" | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+" | sort -u >>TARGET-jldc.txt;curl -s "https://crt.sh/?q=%25.$alvo&output=json" | jq -r '.[].name_value' | sed 's/\*\.//g' | sort -u >>TARGET-crt.txt;curl -s "https://dns.bufferover.run/dns?q=.$alvo" | jq -r .FDNS_A[] | sed -s 's/,/\\n/g'  | sort -u  >>TARGET-bufferover.txt;cat TARGET-*.txt | sort -u >stage4;

var4=$(wc -l stage4)

echo "Stage 4 - Complete - Were found $var4"
sleep 2; 
echo -e
echo -e
#subfinder+assetfinder+amass+subjack
subfinder -d "$alvo" >> stage5 ; assetfinder -subs-only "$alvo" >> stage5 ; amass enum -norecursive -noalts -d "$alvo" >> stage5 ; subjack -w stage5 -t 100 -timeout 30 -ssl -c ~/fingerprints.json -v 3 >> takeoverstage5

var5=$(wc -l stage5)
var5take=$(wc -l takeoverstage5)


echo "Stage 5 - Complete - Were found $var5 and Takeover $var5take"
sleep 2;
echo -e
echo -e
#Assetfinder
assetfinder --subs-only "$alvo" | anew stage6

var6=$(wc -l stage6)

echo "Stage 6 - Complete - Were found $var6"
sleep 2;
echo -e
echo -e
#Gospider
gospider -d 0 -s "https://$alvo" -c 5 -t 100 -d 5 --blacklist jpg,jpeg,gif,css,tif,tiff,png,ttf,woff,woff2,ico,pdf,svg,txt | grep -Eo '(http|https)://[^/"]+' | anew stage7

var7=$(wc -l stage7)

echo "Stage 7 - Complete - Were found $var7"
sleep 2;

echo -e
echo -e

#JLDC
curl -s "https://jldc.me/anubis/subdomains/$alvo" | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+" | anew stage8

var8=$(wc -l stage8)

echo "Stage 8 - Complete - Were found $var8"

sleep 2;

echo -e
echo -e


#Filter domains
cat stage* hosts-amass.txt hosts-crtsh.txt    |  anew subdomain

echo "Stage SUBDOMAIN-FILTER - Complete"
sleep 2;
echo -e
echo -e

#Recon do recon
#findomain-linux -f subdomain -r -u subdomain1

#echo "Stage subdomain1 - Complete"

#sleep 2;
echo -e
echo -e
#xargs -a subdomain -I@ -P5 sh -c 'assetfinder @ | anew subdomains2'

#echo "Stage subdomains2 - Complete"
#sleep 2;
echo -e
echo -e
#xargs -a subdomain -I@ -P20 sh -c 'echo @' | dnsgen - |  anew subdomain3

echo "Stage subdominio3 - Complete"

sleep 2;

echo -e
echo -e

#Regroup

cat subdomain*  | grep "$alvo" | anew subdomainfinal

var9=$(wc -l subdomainfinal)

sleep 2;

#Validate httpx
cat subdomainfinal | httpx -silent -threads 200 timeout 2 -mc 200,301,302 | anew subdomainvalidate

sleep 4;

echo "Stage validate subdomains"

sleep 2;

echo -e
echo -e
echo -e
#Massdns

massdns -r /home/ferramentas/massdns/resolvers.txt -t AAAA subdomainfinal >> stage9

sleep 2;

echo "Stage MassDns - Complete"
echo -e
echo -e

sleep 2;
#Search Bucker

python3 /home/ferramentas/S3Scanner/s3scanner.py -l subdomainvalidate

echo -e
echo -e 
echo -e
echo "Stage Search Bucket s3 - Complete "

sleep 2;

#Aquatone
mkdir aquatone;
echo "Directory aquatone created"

echo -e
echo -e
cat subdomainvalidate | aquatone -ports large -out aquatone/

#Clear domains
cat subdomainvalidate | cut -d "/" -f3 > dominioslimpos

varfinish=$(wc -l dominioslimpos)
echo "Recon the  Recon subdominio finish! - Were found $varfinish"
cd ..
